# Generated by Django 3.2.3 on 2021-07-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210707_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Products.Product'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
