# Generated by Django 3.2.3 on 2021-07-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_order_transaction_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Item',
            new_name='OrderItem',
        ),
    ]
