# Generated by Django 3.2.3 on 2021-07-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_shippingaddress_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
