# Generated by Django 3.2.3 on 2021-07-22 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
