# Generated by Django 3.2.3 on 2021-07-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_contactform_date_submitted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
