# Generated by Django 3.2.3 on 2021-07-08 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Pages',
            new_name='Customer_Page',
        ),
    ]
